// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxiEfuNf0f-B9Dt41K94r7eAN7VuFMToA',
    appId: '1:767482347165:web:308721333d80f8213f5e74',
    messagingSenderId: '767482347165',
    projectId: 'provafaculdadeexercicios1511',
    authDomain: 'provafaculdadeexercicios1511.firebaseapp.com',
    storageBucket: 'provafaculdadeexercicios1511.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPB3LyKLrmx8Q3Opss7FMzt-JUuLhsLm0',
    appId: '1:767482347165:android:f50896783f82029d3f5e74',
    messagingSenderId: '767482347165',
    projectId: 'provafaculdadeexercicios1511',
    storageBucket: 'provafaculdadeexercicios1511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlpQK6UqTt6lDC_VpW9J6GQalGWh0J-Q',
    appId: '1:767482347165:ios:4a837b74cffd41643f5e74',
    messagingSenderId: '767482347165',
    projectId: 'provafaculdadeexercicios1511',
    storageBucket: 'provafaculdadeexercicios1511.appspot.com',
    iosBundleId: 'com.example.provafaculdadeexericios1511',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAlpQK6UqTt6lDC_VpW9J6GQalGWh0J-Q',
    appId: '1:767482347165:ios:e489b7a4597df2483f5e74',
    messagingSenderId: '767482347165',
    projectId: 'provafaculdadeexercicios1511',
    storageBucket: 'provafaculdadeexercicios1511.appspot.com',
    iosBundleId: 'com.example.provafaculdadeexericios1511.RunnerTests',
  );
}
